services:
  app:
    image: abdullahdev904/bookstore-app:v1
    ports:
    - "4000:4000"
    environment:
      PORT: 4000
      REDIS_HOST: redis
      MONGO_URI: mongodb://mongodb:27017/bookstore
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mongo-data: