services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      REDIS_HOST: redis
      MONGO_URI: mongodb://mongodb:27017/bookstore
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  redis:
    image: redis:latest
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru --appendonly yes --requirepass Ab1762919
    ports:
    - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
